################################################################
#               CONFIGURATION VARIABLES HERE                   #
################################################################

######################
#   DATASET CONFIG   #
######################
    # num tfidf
    # include amount and date features 
    # save train and test datasets to not repeat these steps

OUTFLOWS_PATH: data/ucsd-outflows.pqt
INFLOWS_PATH: data/ucsd-inflows.pqt

FEATURES: 
    num_tfidf_features: 5000
    include_date_features: True
    include_amount_features: True

# include file path to save features.pkl to
SAVE_FEATURES: data/features_data.pkl

######################
#    MODEL CONFIG    #
######################

# select the models that you would like to be trained
# TODO: add hyperparameters to rest of models
# TODO: add option to save models
MODELS:
    NON_LLM: 
        log_reg:
            train: True
            hyperparameters:
                penalty: l2
                C: 1.0
        random_forest: 
            train: False
        xgboost: 
            train: False
        svm: 
            train: False
        multnb: 
            train: False
    LLM: 
        bert: 
            train: False
        fasttext: 
            train: False
