name: prism_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - pytorch
  - torchvision
  - torchaudio
  - nltk
  - xgboost
  - fasttext
  - gensim
  - plotly
  - transformers