#########################################################################
#                        CONFIGURATION VARIABLES HERE                   #
#########################################################################

#####################################################
#                DATASET CONFIG                     #
#####################################################
# Input the paths to the necessary datasets
ACCOUNT_DF_PATH: q2_data/q2-ucsd-acctDF.pqt
CONSUMER_DF_PATH: q2_data/q2-ucsd-consDF.pqt
TRANSACTION_DF_PATH: q2_data/q2-ucsd-trxnDF.pqt
CATEGORY_MAP_PATH: q2_data/q2-ucsd-cat-map.csv

#####################################################
#           FEATURE SELECTION CONFIG                #
#####################################################
# Choose a feature selection method below. 
# lasso uses L1 regularization to reduce irrelevant feature weights to 0
# point_biserial uses the point biserial correlation of features to measure the most significant features
# options: lasso, point_biserial
FEATURE_SELECTION: lasso
MAX_FEATURES: 500
# decided whether or not to use credit score as a feature
DROP_CREDIT_SCORE: True

#####################################################
#                  MODEL CONFIG                     #
#####################################################
# For models you would like to train and generate reason codes for, set the respective parameters to True
# ONLY set shap to True if train is True
MODELS:
    LogisticRegression: 
        train: True
        shap: False
    HistGB: 
        train: True
        shap: True
    CatBoost: 
        train: False
        shap: False
    LightGBM: 
        train: False
        shap: False
    XGBoost: 
        train: False
        shap: False

